Repository Cheyenne-Moutain-Computer-Science-Club/spoonSite, pull requests merged in 2023-01, with the labels that each got.

#40 Auth rework
  components/AuthCheck.jsx
  components/errorModal.jsx
  components/navbar.jsx
  components/userProfileDropdown.jsx
  lib/auth.js
  lib/context.js
  lib/firebase.js
  lib/hooks.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].js
  pages/auth/new-user/index.jsx
  pages/index.js
  pages/leaderboard/index.jsx
  pages/tag-report/index.jsx
  pages/team-leaderboard/index.jsx
  public/_firebase.js
Labels: improvement, Failing

#56 It was one wrong import...
  components/AuthCheck.jsx
Labels: Organizational

#53 Aesthetic updates
  components/AuthCheck.jsx
  components/errorModal.jsx
  components/footer.jsx
  components/grid-boxes/tripleBox.jsx
  components/modals/errorModal.jsx
  components/modals/successModal.jsx
  components/navbar.jsx
  components/pageTitle.jsx
  package-lock.json
  pages/rules/index.jsx
  pages/tag-report/index.jsx
  public/interact-logos/interact-logo-blue.png
  public/interact-logos/interact-logo-gray.png
  public/interact-logos/interact-logo-white.png
  public/meta-icons/Next-Dark.svg
  public/meta-icons/Next-Light.svg
  public/meta-icons/React-Dark.svg
  public/meta-icons/React-Light.svg
  public/meta-icons/Tailwind-Dark.svg
  public/meta-icons/Tailwind-Light.svg
  public/statusIndicators/error.png
  public/statusIndicators/tick2.gif
  public/statusIndicators/tickPlayOnce.gif
Labels: bug, improvement, feature missing

#63 Build warn
  components/footer.jsx
  components/modals/errorModal.jsx
  components/modals/successModal.jsx
  components/navbar.jsx
  next.config.js
  pages/_app.js
  pages/index.js
Labels: improvement

#66 Mobile ux improvments
  components/footer.jsx
  components/modals/errorModal.jsx
  components/personCard.jsx
  components/personRow.jsx
  package-lock.json
  package.json
  pages/leaderboard/index.jsx
  public/statusIndicators/warning.png
Labels: improvement

#70 Overflow tweak
  pages/tag-report/index.jsx
Labels: bug

#72 Minor aesthetic updates
  pages/index.js
Labels: improvement
